---
kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: harbor.ntppool.org/ntppool/drone-kaniko:main
  pull: always
  settings:
    dockerfile: base-os/Dockerfile
    context: base-os
    repo: perlorg/base-os
    registry: harbor.ntppool.org
    auto_tag: true
    tags: ${DRONE_SOURCE_BRANCH},SHA7
    cache: true
    username:
      from_secret: harbor_perlorg_username
    password:
      from_secret: harbor_perlorg_password
---
kind: signature
hmac: 36f57dc6dd0802381bd4f9b56a3964aa1461998b8e495426b022f6c6967debb0

...
